-- ═══════════════════════════════════════════════════════════════════════════
-- ABTalks AI Interview Agent — Supabase PostgreSQL Schema & Initial Seed
-- Copy & paste this entire script into your Supabase Dashboard SQL Editor:
-- https://supabase.com/dashboard/project/_/sql/new
-- ═══════════════════════════════════════════════════════════════════════════

-- 1. CANDIDATES TABLE
CREATE TABLE IF NOT EXISTS public.candidates (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    job_role TEXT NOT NULL,
    years_experience INTEGER NOT NULL DEFAULT 1,
    education TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. MISSIONS TABLE (31-day curriculum tracker per candidate)
CREATE TABLE IF NOT EXISTS public.missions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id TEXT NOT NULL REFERENCES public.candidates(id) ON DELETE CASCADE,
    day INTEGER NOT NULL,
    title TEXT NOT NULL,
    passed BOOLEAN NOT NULL DEFAULT false,
    skipped BOOLEAN NOT NULL DEFAULT false,
    attempts INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. LEARNING SIGNALS TABLE
CREATE TABLE IF NOT EXISTS public.learning_signals (
    candidate_id TEXT PRIMARY KEY REFERENCES public.candidates(id) ON DELETE CASCADE,
    commit_days INTEGER NOT NULL DEFAULT 0,
    missions_completed INTEGER NOT NULL DEFAULT 0,
    missions_first_try INTEGER NOT NULL DEFAULT 0,
    avg_daily_hours NUMERIC(4,2) NOT NULL DEFAULT 0.0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 4. INTERVIEW SESSIONS TABLE
CREATE TABLE IF NOT EXISTS public.interview_sessions (
    session_id TEXT PRIMARY KEY,
    candidate_id TEXT NOT NULL REFERENCES public.candidates(id) ON DELETE CASCADE,
    persona TEXT NOT NULL DEFAULT 'engineer',
    status TEXT NOT NULL DEFAULT 'active',
    question_count INTEGER NOT NULL DEFAULT 0,
    difficulty TEXT NOT NULL DEFAULT 'medium',
    started_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    completed_at TIMESTAMPTZ
);

-- 5. CONVERSATION MESSAGES TABLE
CREATE TABLE IF NOT EXISTS public.conversation_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES public.interview_sessions(session_id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    topic TEXT,
    curriculum_day INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 6. RECRUITER VERDICTS TABLE
CREATE TABLE IF NOT EXISTS public.recruiter_verdicts (
    session_id TEXT PRIMARY KEY REFERENCES public.interview_sessions(session_id) ON DELETE CASCADE,
    verdict TEXT NOT NULL,
    confidence INTEGER NOT NULL,
    recruiter_notes TEXT,
    evidence_for_json JSONB DEFAULT '[]'::jsonb,
    evidence_against_json JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- INDEXES FOR FAST QUERY PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_missions_candidate ON public.missions(candidate_id);
CREATE INDEX IF NOT EXISTS idx_messages_session ON public.conversation_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_sessions_candidate ON public.interview_sessions(candidate_id);

-- ENABLE ROW LEVEL SECURITY (RLS) FOR PUBLIC ACCESS
ALTER TABLE public.candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.missions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learning_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interview_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recruiter_verdicts ENABLE ROW LEVEL SECURITY;

-- PUBLIC ANONYMOUS POLICIES (Full CRUD access for frontend & backend demo)
DROP POLICY IF EXISTS "Allow public read candidates" ON public.candidates;
CREATE POLICY "Allow public read candidates" ON public.candidates FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert candidates" ON public.candidates;
CREATE POLICY "Allow public insert candidates" ON public.candidates FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update candidates" ON public.candidates;
CREATE POLICY "Allow public update candidates" ON public.candidates FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public read missions" ON public.missions;
CREATE POLICY "Allow public read missions" ON public.missions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert missions" ON public.missions;
CREATE POLICY "Allow public insert missions" ON public.missions FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read learning_signals" ON public.learning_signals;
CREATE POLICY "Allow public read learning_signals" ON public.learning_signals FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert learning_signals" ON public.learning_signals;
CREATE POLICY "Allow public insert learning_signals" ON public.learning_signals FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read interview_sessions" ON public.interview_sessions;
CREATE POLICY "Allow public read interview_sessions" ON public.interview_sessions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert interview_sessions" ON public.interview_sessions;
CREATE POLICY "Allow public insert interview_sessions" ON public.interview_sessions FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update interview_sessions" ON public.interview_sessions;
CREATE POLICY "Allow public update interview_sessions" ON public.interview_sessions FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public read conversation_messages" ON public.conversation_messages;
CREATE POLICY "Allow public read conversation_messages" ON public.conversation_messages FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert conversation_messages" ON public.conversation_messages;
CREATE POLICY "Allow public insert conversation_messages" ON public.conversation_messages FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read recruiter_verdicts" ON public.recruiter_verdicts;
CREATE POLICY "Allow public read recruiter_verdicts" ON public.recruiter_verdicts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert recruiter_verdicts" ON public.recruiter_verdicts;
CREATE POLICY "Allow public insert recruiter_verdicts" ON public.recruiter_verdicts FOR INSERT WITH CHECK (true);

-- ═══════════════════════════════════════════════════════════════════════════
-- INITIAL SEED DATA (Cohort Candidates)
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO public.candidates (id, name, email, job_role, years_experience, education, status)
VALUES
    ('CAND-001', 'Sarah Jenkins', 'sarah.j@example.com', 'Senior AI Engineer', 5, 'MS Computer Science, Stanford', 'active'),
    ('CAND-002', 'Alex Chen', 'alex.c@example.com', 'Full Stack AI Developer', 3, 'BS Computer Science, UC Berkeley', 'active'),
    ('CAND-003', 'Marcus Vance', 'marcus.v@example.com', 'Machine Learning Engineer', 4, 'BS Electrical Engineering', 'active')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.learning_signals (candidate_id, commit_days, missions_completed, missions_first_try, avg_daily_hours)
VALUES
    ('CAND-001', 28, 26, 22, 3.5),
    ('CAND-002', 20, 18, 14, 2.2),
    ('CAND-003', 15, 12, 8, 1.8)
ON CONFLICT (candidate_id) DO NOTHING;
